# Generated by Django 5.1.3 on 2024-11-14 21:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0002_alter_user_tokens"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="favorite_packs",
            field=models.ManyToManyField(
                blank=True, related_name="favorited_by_users", to="app.pack"
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="favorite_sounds",
            field=models.ManyToManyField(
                blank=True, related_name="favorited_by_users", to="app.sound"
            ),
        ),
    ]
